server:
  port: 9093

spring:  
  cloud:
    services:
      registrationMethod: route
  datasource:
# ELEPHANT SQL PCF
    url: jdbc:postgresql://baasu.db.elephantsql.com:5432/whmpsxcx
    username: whmpsxcx
    password: 8hwWKLx4g7H7s3rqhvOOSSD-RI9HFbeo
    driverClassName: org.postgresql.Driver
    tomcat:
          max-active: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false