spring:
  cloud:
    services:
      registrationMethod: route

    datasource:
      url: jdbc:postgresql://baasu.db.elephantsql.com:5432/cyaulali
      username: cyaulali
      password: yNw3vmJWCKzIfg9VD_hqADTr_FcsOyW0
      driverClassName: org.postgresql.Driver
      tomcat:
        max-active: 2
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false

